chore: simplify usage of the install script (#166)

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -22,6 +22,9 @@
 
 # Install script is heavily based on: https://github.com/Masterminds/glide.sh/blob/master/get
 
+: ${USE_SUDO:="true"}
+: ${UPLIFT_INSTALL_DIR:="/usr/local/bin"}
+
 HAS_CURL="$(type "curl" &> /dev/null && echo true || echo false)"
 HAS_WGET="$(type "wget" &> /dev/null && echo true || echo false)"
 
@@ -64,27 +67,31 @@ canDownload() {
 }
 
 download() {
-  if [ "${HAS_CURL}" == "true" ]; then
-    VERSION="$(curl -s https://api.github.com/repos/gembaadvantage/uplift/releases/latest | grep "tag_name" | cut -d'v' -f2 | cut -d'"' -f1)"
-  elif [ "${HAS_WGET}" == "true" ]; then
-    VERSION="$(wget -q https://api.github.com/repos/gembaadvantage/uplift/releases/latest -O - 2>&1 | grep "tag_name" | cut -d'v' -f2 | cut -d'"' -f1)"
+  if [ -z "$DESIRED_VERSION" ]; then
+    if [ "${HAS_CURL}" == "true" ]; then
+      TAG="v$(curl -s https://api.github.com/repos/gembaadvantage/uplift/releases/latest | grep "tag_name" | cut -d'v' -f2 | cut -d'"' -f1)"
+    elif [ "${HAS_WGET}" == "true" ]; then
+      TAG="v$(wget -q https://api.github.com/repos/gembaadvantage/uplift/releases/latest -O - 2>&1 | grep "tag_name" | cut -d'v' -f2 | cut -d'"' -f1)"
+    fi
+  else
+    TAG=${DESIRED_VERSION}
   fi
 
-  echo "Attempting to download uplift v${VERSION}..."
+  echo "Attempting to download uplift ${TAG}..."
 
   PACKAGE_TYPE="tar.gz"
   if [ "${OS}" == "windows" ]; then
     PACKAGE_TYPE="zip"
   fi
 
-  local archive="uplift_${VERSION}_${OS}-${ARCH}.${PACKAGE_TYPE}"
+  local archive="uplift_${TAG#v}_${OS}-${ARCH}.${PACKAGE_TYPE}"
 
-  DOWNLOAD_URL="https://github.com/gembaadvantage/uplift/releases/download/v${VERSION}/${archive}"
+  DOWNLOAD_URL="https://github.com/gembaadvantage/uplift/releases/download/${TAG}/${archive}"
   DOWNLOAD_DIR="$(mktemp -dt uplift-install-XXXXXXX)"
   UPLIFT_FILE="${DOWNLOAD_DIR}/${archive}"
 
   if [ "${HAS_CURL}" == "true" ]; then
-    curl -SsL "$DOWNLOAD_URL" -o "$UPLIFT_FILE"
+    curl -L "$DOWNLOAD_URL" -o "$UPLIFT_FILE"
   elif [ "${HAS_WGET}" == "true" ]; then
     wget -q -O "$UPLIFT_FILE" "$DOWNLOAD_URL"
   fi
@@ -93,15 +100,24 @@ download() {
 install() {
   echo "Installing uplift..."
 
-  local extract_dir="$DOWNLOAD_DIR/uplift-$VERSION"
+  local extract_dir="$DOWNLOAD_DIR/uplift-$TAG"
   mkdir -p $extract_dir
   tar xf "$UPLIFT_FILE" -C "${extract_dir}"
-  cp "${extract_dir}/uplift" "/usr/local/bin/uplift"
+  runAsRoot cp "${extract_dir}/uplift" "${UPLIFT_INSTALL_DIR}/uplift"
 
-  echo "Installed uplift to /usr/local/bin"
+  echo "Installed uplift to ${UPLIFT_INSTALL_DIR}"
+}
+
+runAsRoot() {
+  if [ $EUID -ne 0 -a "$USE_SUDO" = "true" ]; then
+    sudo "${@}"
+  else
+    "${@}"
+  fi
 }
 
 tidy() {
+
   if [[ -d "${DOWNLOAD_DIR:-}" ]]; then
     rm -rf "$DOWNLOAD_DIR"
   fi
@@ -111,14 +127,14 @@ verify() {
   set +e
   UPLIFT="$(command -v uplift)"
   if [ "$?" = "1" ]; then
-    echo "Uplift not found. Is $UPLIFT_INSTALL_DIR on your "'$PATH?'
+    echo "Uplift not found. Is ${UPLIFT_INSTALL_DIR} on your "'$PATH?'
     exit 1
   fi
 
   # Test version
   INSTALLED_VERSION="$(uplift version --short)"
-  if [ "${INSTALLED_VERSION}" != "v${VERSION}" ]; then
-    echo "Found version $INSTALLED_VERSION of uplift and not expected installed version of $VERSION"
+  if [ "${INSTALLED_VERSION}" != "${TAG}" ]; then
+    echo "Found version ${INSTALLED_VERSION} of uplift and not expected installed version of $TAG"
     exit 1
   fi
   set -e
@@ -133,8 +149,45 @@ bye() {
 	exit $result
 }
 
+help () {
+  echo "Uplift Installer"
+  echo
+  echo "Flags:"
+  echo -e "  -h, --help     print help for the uplift installer"
+  echo -e "  -v, --version  download and install a specific version of uplift (default 'latest')"
+  echo -e "      --no-sudo  install uplift without using sudo"
+}
+
 trap "bye" EXIT
 set -e
+
+# Parsing input arguments (if any)
+export INPUT_ARGUMENTS="${@}"
+set -u
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    '--version'|-v)
+       shift
+       if [[ $# -ne 0 ]]; then
+           export DESIRED_VERSION="${1}"
+       else
+           echo -e "Please provide a valid version: e.g. --version v2.6.0 or -v v2.6.0"
+           exit 0
+       fi
+       ;;
+    '--no-sudo')
+       USE_SUDO="false"
+       ;;
+    '--help'|-h)
+       help
+       exit 0
+       ;;
+    *) exit 1
+       ;;
+  esac
+  shift
+done
+set +u
 
 initArch
 initOS
